android_binary(
  name = 'app',
  manifest = 'AndroidManifest.xml',
  manifest_entries = {
    'version_code': 1,
    'version_name': '1.0',
    'min_sdk_version': 25,
    'target_sdk_version': 22  #damn you runtime perms
  },
  keystore = ':debug_keystore',
  deps = [
    '//java/com/joshruesch/simswitcher:activity',
    '//res/com/joshruesch/simswitcher:res',
  ],
)

keystore(
  name = 'debug_keystore',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
)
